version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Backend Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Frontend Docker
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Shared
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
